// flow-typed signature: 2d1866db340d3096c3457af66f83a5fa
// flow-typed version: <<STUB>>/prettier-tslint_v^0.4.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-tslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-tslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-tslint/bin/prettier-tslint' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/check' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/cli' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/create-ignorer' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/create-program' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/expand-globs' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/fix' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/format' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/index' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/run-prettier' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/run-tslint' {
  declare module.exports: any;
}

declare module 'prettier-tslint/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-tslint/bin/prettier-tslint.js' {
  declare module.exports: $Exports<'prettier-tslint/bin/prettier-tslint'>;
}
declare module 'prettier-tslint/dist/check.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/check'>;
}
declare module 'prettier-tslint/dist/cli.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/cli'>;
}
declare module 'prettier-tslint/dist/create-ignorer.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/create-ignorer'>;
}
declare module 'prettier-tslint/dist/create-program.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/create-program'>;
}
declare module 'prettier-tslint/dist/expand-globs.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/expand-globs'>;
}
declare module 'prettier-tslint/dist/fix.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/fix'>;
}
declare module 'prettier-tslint/dist/format.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/format'>;
}
declare module 'prettier-tslint/dist/index.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/index'>;
}
declare module 'prettier-tslint/dist/run-prettier.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/run-prettier'>;
}
declare module 'prettier-tslint/dist/run-tslint.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/run-tslint'>;
}
declare module 'prettier-tslint/dist/utils.js' {
  declare module.exports: $Exports<'prettier-tslint/dist/utils'>;
}
